[package]
name = "permswatcher"
version = "0.1.0"
authors = ["Andy Georges <itkovian@gmail.com>"]

[dependencies]
clap = "2.17.1"
notify = "3.0.0"
regex = "0.1"
rustc-serialize = "0.3.19"
slog = "1.2"
slog-json = "1.2.0"
slog-term = "1.3.3"
slog-scope = "0.2.0"
version = "2.0.1"

